autoservisas/autoservisas/urls.py
from django.contrib import admin
from django.urls import path, include
from django.http import HttpResponse
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView


def fake(request):
    return HttpResponse("fake page")


urlpatterns = [
    path("autoservisas_app/", include("autoservisas_app.urls")),
    path("admin/", admin.site.urls),
    path("", RedirectView.as_view(url="autoservisas_app/", permanent=False)),    
    path('user_profile/', include('user_profile.urls')),
    path("accounts/", include("django.contrib.auth.urls")),
    path("tinymce/", include("tinymce.urls")),
    path('i18n/', include('django.conf.urls.i18n')),
    path('rosetta/', include('rosetta.urls')),
] + (
    static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

autoservisas/autoservisas_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("cars/", views.cars, name="cars"),
    path("cars/<int:car_id>", views.car, name="car"),
    path("orders/", views.OrderListView.as_view(), name="orders"),
    path("orders/<int:pk>", views.OrderDetailView.as_view(), name="order-detail"),
    path("search/", views.search, name="search"),
    path("myorders/", views.ServiceOrdersByUserListView.as_view(), name="my-orders"),
    path("myorders/<int:pk>/", views.OrderByUserDetailView.as_view(), name="my-order"),
    path(
        "myorders/<int:pk>/update/",
        views.OrderByUserUpdateView.as_view(),
        name="my-order-update",
    ),
    path(
        "myorders/<int:pk>/delete/",
        views.OrderByUserDeleteView.as_view(),
        name="my-order-delete",
    ),
    path("myorders/new/", views.OrderByUserCreateView.as_view(), name="my-orders-new"),
    path("register/", views.register, name="register"),
]

autoservisas/autoservisas_app/models.py
from django.db import models
from django.urls import reverse
from django.db.models import Sum
from django.contrib.auth.models import User
from datetime import date
from tinymce.models import HTMLField
from django.utils.translation import gettext_lazy as _


class CarModel(models.Model):
    make = models.CharField(
        _("Make"),
        max_length=200,
        help_text=_("Enter make (e.g. Daewoo)"),
    )
    model = models.CharField(
        _("Model"),
        max_length=200,
        help_text=_("Enter model (e.g. Matiz)"),
    )
    car_photo = models.ImageField(_("Car photo"), upload_to="car_photos", null=True)

    def __str__(self):
        return f"{self.make} {self.model}"

    def display_car(self):
        return ", ".join(str(car.license_plate) for car in self.cars.all()[:3])

    display_car.short_description = _("Car")

    class Meta:
        db_table = "Automobilio_modelis"
        verbose_name = _("Model")
        verbose_name_plural = _("Models")


class Car(models.Model):

    car_model = models.ForeignKey(
        CarModel, on_delete=models.RESTRICT, related_name="cars"
    )
    license_plate = models.CharField(
        _("Plate_number"),
        max_length=200,
        help_text=_("Enter plate number"),
    )
    vin_number = models.CharField(
        _("VIN"),
        max_length=200,
        help_text=_("Enter car's plate number"),
    )
    client = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    description = HTMLField(default="")

    def __str__(self):
        return f"{self.client} {self.license_plate}"

    def display_order(self):
        return ", ".join(str(order.id) for order in self.orders.all())

    display_order.short_description = _("Order")

    class Meta:
        db_table = "Automobilis"


class Service(models.Model):
    price = models.FloatField(_("Price"), help_text=_("Enter service price"))
    name = models.CharField(
        _("Service title"),
        max_length=200,
        help_text=_("Enter service title (e.g. Change wheels)"),
    )

    def __str__(self):
        return f"{self.name}"

    def get_absolute_url(self):
        """Nurodo konkretaus aprašymo galinį adresą"""
        return reverse("orderrow-detail", args=[str(self.id)])

    class Meta:
        db_table = "Paslauga"


class OrderQuerySet(models.QuerySet):
    # def my_orders(self, user):
    #     return self.filter(car_owner=user)

    def done(self):
        return self.filter(status__exact="5")

    def order_by_due_back(self):
        return self.order_by("due_back")

    def in_progress_or_done(self):
        return self.filter(models.Q(status__exact="5") | models.Q(status__exact="3"))

    # def taken_books_read_by_me_ordered_by_due_back(self, user):
    #     return self.done().my_orders(user).order_by_due_back()


class Order(models.Model):
    objects = OrderQuerySet.as_manager()
    car_owner = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, blank=True
    )
    car = models.ForeignKey(Car, on_delete=models.RESTRICT, related_name="orders")
    date = models.DateField(
        _("Date"), help_text=_("Date of received order"), auto_now_add=True
    )
    amount = models.FloatField(
        _("Amount"), help_text=_("Leave empty"), null=True, blank=True
    )
    service = models.ManyToManyField(Service, through="OrderRow")
    due_back = models.DateField(_("Due_back"), null=True, blank=True)

    ORDER_STATUS = (
        ("1", _("Received")),
        ("2", _("Accepted")),
        ("3", _("In progress")),
        ("4", _("Overdue")),
        ("5", _("Done")),
    )

    status = models.CharField(
        max_length=1,
        choices=ORDER_STATUS,
        blank=True,
        default="1",
        help_text=_("Status"),
    )

    def __str__(self):
        return f"{self.id}"

    def get_absolute_url(self):
        """Nurodo konkretaus aprašymo galinį adresą"""
        return reverse("order-detail", args=[str(self.id)])

    def display_service(self):
        return ", ".join(service.name for service in self.service.all())

    display_service.short_description = _("Service")

    def total_sum(self):
        orders_amount = self.order_rows.aggregate(Sum("price"))
        return orders_amount["price__sum"]

    # def update_order_amount(self):
    #     self.amount = self.total_sum()
    #     return self.amount

    def save(self, *args, **kwargs):
        self.amount = self.total_sum()
        super().save(*args, **kwargs)

    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False

    class Meta:
        db_table = "Uzsakymas"


class OrderRow(models.Model):

    service = models.ForeignKey(
        Service, on_delete=models.RESTRICT, related_name="service"
    )
    order = models.ForeignKey(
        Order, on_delete=models.CASCADE, related_name="order_rows"
    )
    quantity = models.IntegerField(
        _("Quantity"), help_text=_("Enter quantity"), default=0
    )
    price = models.FloatField(_("Price"), help_text=_("Leave empty"), default=0)

    def __str__(self):
        return f"{self.quantity} {self.price}"

    def get_absolute_url(self):
        """Nurodo konkretaus aprašymo galinį adresą"""
        return reverse("orderrow-detail", args=[str(self.id)])

    @property
    def update_order_price(self):
        self.price = self.quantity * self.service.price
        return self.price

    def save(self, *args, **kwargs):
        self.price = self.update_order_price
        super().save(*args, **kwargs)
        self.order.save()

    class Meta:
        db_table = "Uzsakymo_eilute"


class OrderReview(models.Model):
    order = models.ForeignKey("Order", on_delete=models.RESTRICT, null=True, blank=True)
    reviewer = models.ForeignKey(User, on_delete=models.RESTRICT, null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add=True)
    content = models.TextField(_("Review"), max_length=2000)

autoservisas/autoservisas_app/forms.py
from .models import OrderReview, Order
from django import forms


class OrderReviewForm(forms.ModelForm):
    class Meta:
        model = OrderReview
        fields = (
            "content",
            "order",
            "reviewer",
        )
        widgets = {"order": forms.HiddenInput(), "reviewer": forms.HiddenInput()}


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = (
            "car",
            "service",
        )

autoservisas/autoservisas_app/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Car, CarModel, Service, Order
from django.views import generic
from django.core.paginator import Paginator
from django.db.models import Q
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.forms import User
from django.views.decorators.csrf import csrf_protect
from django.contrib import messages
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from .forms import OrderReviewForm, OrderForm
from django.views.generic.edit import FormMixin
from datetime import date, timedelta


def index(request):
    num_services = Service.objects.all().count()
    completed_orders = Order.objects.filter(status__exact="5")
    num_completed_orders = completed_orders.count()
    num_cars = Car.objects.count()
    num_visits = request.session.get("num_visits", 1)
    request.session["num_visits"] = num_visits + 1

    context = {
        "num_services": num_services,
        "num_completed_orders": num_completed_orders,
        "num_cars": num_cars,
        "num_visits": num_visits,
    }

    return render(request, "index.html", context=context)


def cars(request):
    paginator = Paginator(CarModel.objects.all(), 2)
    page_number = request.GET.get("page")
    paged_cars = paginator.get_page(page_number)
    # cars = CarModel.objects.all()
    context = {"cars": paged_cars}
    return render(request, "cars.html", context=context)


def car(request, car_id):
    car = get_object_or_404(CarModel, pk=car_id)
    return render(request, "car.html", {"car": car})


def search(request):
    query = request.GET.get("query")
    query_filter = (
        Q(client__icontains=query)
        | Q(license_plate__icontains=query)
        | Q(vin_number__icontains=query)
        | Q(car_model__model__icontains=query)
    )
    search_results = Car.objects.filter(query_filter)
    return render(
        request, "search.html", {"cars_filter": search_results, "query": query}
    )


@csrf_protect
def register(request):
    if request.method == "POST":
        # pasiimame reikšmes iš registracijos formos
        username = request.POST["username"]
        email = request.POST["email"]
        password = request.POST["password"]
        password2 = request.POST["password2"]
        # tikriname, ar sutampa slaptažodžiai
        if password == password2:
            # tikriname, ar neužimtas username
            if User.objects.filter(username=username).exists():
                messages.error(request, _("Username %s already exists!") % username)
                return redirect("register")
            else:
                # tikriname, ar nėra tokio pat email
                if User.objects.filter(email=email).exists():
                    messages.error(request, _("Email %s already exists!") % email)
                    return redirect("register")
                else:
                    # jeigu viskas tvarkoje, sukuriame naują vartotoją
                    User.objects.create_user(
                        username=username, email=email, password=password
                    )
        else:
            messages.error(request, _("Passwords do not match!"))
            return redirect("register")
    return render(request, "register.html")


class OrderListView(generic.ListView):
    model = Order
    paginate_by = 10
    template_name = "order_list.html"
    context_object_name = "order_list"

    def get_queryset(self):
        return Order.objects.all()


class ServiceOrdersByUserListView(LoginRequiredMixin, generic.ListView):
    model = Order
    context_object_name = "orders"
    template_name = "my_orders.html"
    paginate_by = 10

    def get_queryset(self):
        # Order.objects.taken_books_read_by_me_ordered_by_due_back()
        # Order.objects.done().order_by_due_back().my_orders()
        # Order.objects.filter(car_owner=self.request.user).filter(status__exact='p').order_by('due_back')
        return (
            Order.objects.filter(car_owner=self.request.user)
            .in_progress_or_done()
            .order_by_due_back()
        )


class OrderByUserDetailView(LoginRequiredMixin, generic.DetailView):
    model = Order
    template_name = "user_order.html"


class OrderDetailView(FormMixin, generic.DetailView):
    model = Order
    template_name = "order_detail.html"
    form_class = OrderReviewForm

    class Meta:
        ordering = ["title"]

    # nurodome, kur atsidursime komentaro sėkmės atveju.
    def get_success_url(self):
        return reverse_lazy("order-detail", kwargs={"pk": self.object.id})

    # standartinis post metodo perrašymas, naudojant FormMixin, galite kopijuoti tiesiai į savo projektą.
    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    # štai čia nurodome, kad knyga bus būtent ta, po kuria komentuojame, o vartotojas bus tas, kuris yra prisijungęs.
    def form_valid(self, form):
        form.instance.order = self.object
        form.instance.reviewer = self.request.user
        form.save()
        return super(OrderDetailView, self).form_valid(form)


class OrderByUserCreateView(LoginRequiredMixin, generic.CreateView):
    model = Order
    form_class = OrderForm
    success_url = reverse_lazy("my-orders")
    template_name = "user_order_form.html"

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.fields["car"].queryset = Car.objects.filter(client=self.request.user)
        return form

    def form_valid(self, form):
        form.instance.car_owner = self.request.user
        form.instance.status = "3"
        return super().form_valid(form)

    # def get_initial(self):
    #     initial = super().get_initial()
    #     order_id = self.request.GET.get('order_id')
    #     if order_id:
    #         initial['order'] = order_id
    #     initial['due_back'] = date.today() + timedelta(days=3)
    #     return initial


class OrderByUserUpdateView(
    LoginRequiredMixin, UserPassesTestMixin, generic.UpdateView
):
    model = Order
    form_class = OrderForm
    success_url = reverse_lazy("my-orders")
    template_name = "user_order_form.html"

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.fields["car"].queryset = Car.objects.filter(client=self.request.user)
        return form

    def form_valid(self, form):
        form.instance.car_owner = self.request.user
        form.instance.status = "3"
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["is_update"] = True
        return context

    # def get_initial(self):
    #     initial = super().get_initial()
    #     initial['due_back'] = date.today() + timedelta(days=7)
    #     return initial

    def test_func(self):
        return (
            self.request.user == self.get_object().car_owner
            and self.get_object().status != "5"
        )


class OrderByUserDeleteView(
    LoginRequiredMixin, UserPassesTestMixin, generic.DeleteView
):
    model = Order
    success_url = reverse_lazy("my-orders")
    template_name = "user_order_delete.html"

    def form_valid(self, form):
        messages.success(self.request, f'{_("Order deleted").capitalize()}')
        return super().form_valid(form)

    def test_func(self):
        return self.request.user == self.get_object().car_owner

autoservisas/autoservisas_app/templates/base.html
<!DOCTYPE html>{% load static i18n %}
<html lang="{% get_current_language as LANGUAGE_CODE %}{{ LANGUAGE_CODE }}">

<head>
    {% block title %}
    <title>{% trans "autoservice"|capfirst %}</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <!-- Add additional CSS in static file -->
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light static-top mb-5 shadow">
        <div class="container">
            <a class="navbar-brand" href="#">
                <img src="https://svgsilh.com/svg/2386838.svg" style="width:2em; height:2em"> {% trans "autoservice"|capfirst %}
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'index' %}">{% trans "home"|capfirst %}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'orders' %}">{% trans "all orders"|capfirst %}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'cars' %}">{% trans "all cars"|capfirst %}</a>
                    </li>
                </ul>
                <ul class="navbar-nav ml-auto">
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <svg class="bi bi-person" width="1.5em" height="1.5em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                      <path fill-rule="evenodd" d="M13 14s1 0 1-1-1-4-6-4-6 3-6 4 1 1 1 1h10zm-9.995-.944v-.002.002zM3.022 13h9.956a.274.274 0 00.014-.002l.008-.002c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664a1.05 1.05 0 00.022.004zm9.974.056v-.002.002zM8 7a2 2 0 100-4 2 2 0 000 4zm3-2a3 3 0 11-6 0 3 3 0 016 0z" clip-rule="evenodd"/>
                    </svg> {{ user.get_username }}</a>
                    </li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'my-orders'%}">{% trans "my orders"|capfirst %}</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'my-orders-new'%}?next={{request.path}}">{% trans "new"|capfirst %}</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'my-profile' %}">{% trans "profile"|capfirst %}</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'logout'%}?next={% url 'index' %}">{% trans "logout"|capfirst %}</a></li>
                    {% else %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'login' %}?next={{request.path}}">{% trans "login"|capfirst %}</a></li>
                    {% endif %} {% if not user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'register' %}">{% trans "register"|capfirst %}</a></li>
                    {% endif %}

                    <form class="form-inline my-2 my-lg-0" action="{% url 'search' %}" method="get">
                        <input class="form-control mr-sm-2" type="search" placeholder="Paieška" aria-label="Search" name="query">
                        <button class="btn btn-outline-info my-2 my-sm-0" type="submit">{% trans "search"|capfirst %}</button>
                    </form>
                    </li>
                    {% if user.is_authenticated and user.is_superuser %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'admin:index' %}">{% trans "admin"|capfirst %}</a></li>
                    {% endif %}
                </ul>
                <form action="{% url 'set_language' %}" method="post">
                    {% csrf_token %}
                    <select name="language" class="form-control" onchange="this.form.submit()">
                      {% get_available_languages as LANGUAGES %}
                      {% for lang in LANGUAGES %}
                        <option value="{{ lang.0 }}" {% if lang.0 == LANGUAGE_CODE %} selected=selected{% endif %}>
                        {{ lang.1 }}</options>
                      {% endfor %}
                    </select> {% comment %} <button type="submit" class="btn btn-outline-primary">{% trans "GO" %}</button> {% endcomment %}
                </form>
            </div>
        </div>
    </nav>

    <div class="container">
        {% if messages %} {% for message in messages %}
        <div class="alert alert-{{ message.tags }}" role="alert">
            {{ message }}
        </div>
        {% endfor %} {% endif %} {% block content %}{% endblock %}</div>
</body>

</html>

autoservisas/autoservisas_app/templates/car.html
{% extends "base.html" %} {% load i18n %} {% block content %}
<div class="container car">
    <h4>{{ car.make }} {{ car.model }}</h4>
    </br>
    <img src="{{ car.car_photo.url }}" style="margin-bottom: 20px;">
    <h5>{% blocktrans %}Information about car {{ car.make }} {{ car.model }}:{% endblocktrans %}</h5>
    {% for car_information in car.cars.all %}
    <li>{% trans "Client:" %} {{ car_information.client }}</li>
    <li>{% trans "Plate number:" %} {{ car_information.license_plate }}</li>
    <li>{% trans "Car VIN number:" %} {{ car_information.vin_number }}</li>
    <h6>{% trans "Description:" %}</h6>
    <p>{{ car_information.description | safe }}</p>
    {% endfor %}
</div>
{% endblock %}

autoservisas/autoservisas_app/templates/cars.html
{% extends "base.html" %} {% load static i18n %} {% block content %}
<h1>{% trans "Cars" %}</h1>
<p>{% trans "List of cars registered in our shop." %}</p>
{% if cars %}
<div class="row">
    {% for car in cars %}
    <div class="col-md-4 d-flex align-items-stretch">
        <div class="card mb-4 shadow-sm">
            {% if car.car_photo %}
            <img src="{{ car.car_photo.url }}" class="card-img-top" alt="..."> {% else %}
            <img src="{% static 'img/no-image.png' %}" class="card-img-top"> {% endif %}
            <div class="card-body">
                <h6 class="card-subtitle mb-2 text-muted">{{ car.model }}</h6>
                <p class="card-text"><a href="{{ car.id }}">{{ car.make }}</a></p>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endif %}
<div class="container puslapiai">
    <nav aria-label="...">
        {% if cars.has_other_pages %}
        <ul class="pagination pagination-sm justify-content-end">
            {% for i in cars.paginator.page_range %} {% if cars.number == i %}
            <li class="page-item active">
                <a class="page-link" href ">{{ i }}</a>
                        </li>
                    {% else %}
                        <li class="page-item ">
                            <a class="page-link " href="?page={{ i }} ">{{ i }}</a>
                        </li>
                    {% endif %}
                {% endfor %}
            </ul>
        {% endif %}
    </nav>
  </div>
{% endblock %}

autoservisas/autoservisas_app/templates/index.html
{% extends "base.html" %} {% load i18n %} {% block content %}
<h1>{% trans "Auto service" %}</h1>
<p>{% trans "Welcome back to the auto service!" %}</p>
<p>{% trans "Our auto service stats:" %}</p>
<ul>
    <li><strong>{% trans "Available services amount:" %}</strong> {{ num_services }}</li>
    <li><strong>{% trans "Finished orders amount:" %}</strong> {{ num_completed_orders }}</li>
    <li><strong>{% trans "Cars amount:" %}</strong> {{ num_cars }}</li>
</ul>
<p>{% blocktrans %}You visited our page {{ num_visits }} times.{% endblocktrans %}</p>
{% endblock %}

autoservisas/autoservisas_app/templates/my_orders.html
{% extends "base.html" %} {% load i18n %} {% block content %}
<h1>{% trans "my orders"|capfirst %}</h1>

{% if orders %}
<ul>

    {% for order in orders %}
    <li class="{% if order.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'my-order' order.pk %}">
            <img class="rounded-circle" src="{{ order.car_owner.profile.picture.url }}" width="50"> {{ order.car_owner }}
        </a>
        <a href="{% url 'order-detail' order.pk %}">{{order.date}}</a> ({{ order.display_service }} {% if order.due_back != None %} {% trans "Due back:" %} {{ order.due_back }}) {% else %} ) {% endif %}
    </li>
    {% endfor %}
</ul>

{% else %}
<p>{% trans "You do not have orders at the moment." %}</p>
{% endif %} {% endblock %}

autoservisas/autoservisas_app/templates/order_detail.html
{% extends "base.html" %} {% load i18n %} {% block content %}
<h1>{{ order.car }}</h1>

<p><strong>{% trans "Car:" %}</strong> <a href="{% url 'car' order.car.pk %}">{{ order.car }}</a></p>
<p><strong>{% trans "Amount:" %}</strong> {{ order.amount }}</p>
<p><strong>{% trans "Date:" %}</strong> {{ order.date }}</p>
<p class="{% if order.status == '5' %}text-success{% elif order.status == '4' %}text-danger{% else %}text-warning{% endif %}">
    <strong>{% trans "Order status:" %}</strong> {{ order.get_status_display }}
</p>

<div style="margin-left:20px;margin-top:20px">
    <h4>{% trans "Order details:" %}</h4>


    {% for order in order.order_rows.all %}
    <p><strong>{% trans "ID:" %}</strong> {{ order.id }}</p>
    <p><strong>{% trans "Service:" %}</strong> {{ order.service }}</p>
    <p><strong>{% trans "Quantity:" %}</strong> {{ order.quantity }}</p>
    <p><strong>{% trans "Price:" %}</strong> {{ order.price }}</p>
    {% endfor %}
</div>
</br>
<h4>{% trans "Reviews:" %}</h4>
{% if order.orderreview_set.all %} {% for review in order.orderreview_set.all %}
<hr>
<strong>{{ review.reviewer }}</strong>, <em>{{ review.date_created}}</em>
<p>{{ review.content }}</p>
{% endfor %} {% else %}
<p>{% trans "Order does not have any reviews" %}</p>

{% endif %} {% if user.is_authenticated %}
<div class="fieldWrapper">
    <hr><br/>
    <h4>{% trans "Leave review:" %}</h4>
    <form action="" method="post">
        {% csrf_token %} {{ form.content }}</br>
        <input type="submit" value="{% trans "Save" %}">
    </form>
</div>
{% endif %} {% endblock %}

autoservisas/autoservisas_app/templates/order_list.html
{% extends "base.html" %} {% load i18n %} {% block content %}
<h1>{% trans "Order list" %}</h1>
{% if order_list %}
<ul>
    {% for order in order_list %}
    <img class="rounded-circle" src="{{order.car_owner.profile.picture.url}}">
    <li>
        <a href="{{ order.id }}">{{ order.car }} {{ order.display_service }} {{ order.amount }} ({{order.date}})</a>
    </li>
    {% endfor %}
</ul>
{% else %}
<p>{% trans "No orders yet." %}</p>
{% endif %}
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; {% trans "first" %}</a>
            <a href="?page={{ page_obj.previous_page_number }}">{% trans "back" %}</a>
        {% endif %}

        <span class="current">
            {% blocktrans %}{{ page_obj.number }} out of {{ page_obj.paginator.num_pages }}{% endblocktrans %}
        </span> {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}">{% trans "forward" %}</a>
    <a href="?page={{ page_obj.paginator.num_pages }}">{% trans "last" %} &raquo;</a> {% endif %}
    </span>
</div>
{% endblock %}

autoservisas/autoservisas_app/templates/search.html
{% extends "base.html" %} {% load i18n %} {% block content %}
<h1>{% blocktrans %}Search results for '{{ query }}':{% endblocktrans %}</h1>
</br>
{% if cars_filter %}
<ul>
    {% for car in cars_filter %}
    <li>
        <a href="{% url 'car' car.id %}">{{car.car_model}}</a> ({{ car.client }} {{car.license_plate}} {{car.vin_number}})
    </li>
    {% endfor %}
</ul>
{% else %}
<p>{% trans "Oops. We didn't find anything :(" %}</p>
{% endif %} {% endblock %}